"""Loudness envelope of an audio file, as a script the studio loads next to a scene, for audio-reactive visuals
(waveforms, things that pulse with a voice, mouths that move while someone talks).

Usage:
    python tools/audio_envelope.py <audio file> --id=my_voice [--fps=30] [--out=projects/my_voice.env.js]

Writes `registerEnvelope('<id>', fps, values)` with values 0..1; read it in a scene with envelopeAt('<id>', t).
Needs ffmpeg on PATH and numpy.
"""
import json
import os
import subprocess
import sys

import numpy as np

SR = 22050


def main():
    args = [a for a in sys.argv[1:] if not a.startswith("--")]
    opts = dict(a[2:].split("=", 1) for a in sys.argv[1:] if a.startswith("--") and "=" in a)
    if not args or "id" not in opts:
        print(__doc__)
        sys.exit(1)
    fps, env_id = float(opts.get("fps", 30)), opts["id"]
    root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    out = opts.get("out", os.path.join(root, "projects", f"{env_id}.env.js"))
    raw = subprocess.run(["ffmpeg", "-v", "error", "-i", args[0], "-ac", "1", "-ar", str(SR), "-f", "f32le", "-"], check=True, capture_output=True).stdout
    y = np.frombuffer(raw, dtype=np.float32)
    hop = int(SR / fps)
    rms = np.array([np.sqrt(np.mean(y[i:i + hop] ** 2)) for i in range(0, len(y) - hop, hop)])
    values = np.round(rms / (np.percentile(rms, 98) or 1), 3).clip(0, 1)
    os.makedirs(os.path.dirname(out) or ".", exist_ok=True)
    with open(out, "w", encoding="utf-8") as f:
        f.write(f"// Generated by tools/audio_envelope.py from {os.path.basename(args[0])}.\n")
        f.write(f"registerEnvelope({json.dumps(env_id)}, {fps:g}, {json.dumps(values.tolist())});\n")
    print(f"{out}: {len(values)} values at {fps:g} fps ({len(values) / fps:.2f} s)")


if __name__ == "__main__":
    main()
