"""Spoken narration from a script, with word timings, for explainer videos and voice-overs.

Usage:
    python tools/narrate.py projects/my_video.narration.txt --id=my_video [--voice=es-AR-TomasNeural] [--rate=+0%]
                            [--pause=0.7] [--out=projects/my_video.voice.wav]

The script is split into blocks, each starting with a line `[block id]` (optionally `[block id] pause=1.5`, the silence
after that block). Every block is synthesised on its own with edge-tts (Microsoft's online voices: the text is sent to
their service, no key needed; the voice is spoken, never sung), and the blocks are joined with their pauses.

Writes the voice as a WAV and `registerLyrics('<id>', lines)` next to it (projects/<id>.lyrics.js), one line per block:
{ id, t0, t1, words: [[t0, t1, word], ...] }, so a scene can time its shots to blocks (by id) and its details to words
(wordAt). Lines starting with # are comments.
"""
import asyncio
import json
import os
import subprocess
import sys

import numpy as np
import scipy.io.wavfile as wavfile
import edge_tts

SR = 24000


def parse(path, default_pause):
    blocks, cur = [], None
    for raw in open(path, encoding="utf-8"):
        line = raw.strip()
        if line.startswith("#"):
            continue
        if line.startswith("["):
            head, _, rest = line[1:].partition("]")
            opts = dict(kv.split("=", 1) for kv in rest.split() if "=" in kv)
            cur = {"id": head.strip(), "text": "", "pause": float(opts.get("pause", default_pause))}
            blocks.append(cur)
        elif line and cur is not None:
            cur["text"] += (" " if cur["text"] else "") + line
    return [b for b in blocks if b["text"]]


async def speak(text, voice, rate):
    audio, words = bytearray(), []
    async for chunk in edge_tts.Communicate(text, voice, rate=rate, boundary="WordBoundary").stream():
        if chunk["type"] == "audio":
            audio += chunk["data"]
        elif chunk["type"] == "WordBoundary":
            t0 = chunk["offset"] / 1e7
            words.append([round(t0, 3), round(t0 + chunk["duration"] / 1e7, 3), chunk["text"]])
    pcm = subprocess.run(["ffmpeg", "-v", "error", "-i", "pipe:0", "-ac", "1", "-ar", str(SR), "-f", "f32le", "-"],
                         input=bytes(audio), check=True, capture_output=True).stdout
    return np.frombuffer(pcm, dtype=np.float32), words


def main():
    args = [a for a in sys.argv[1:] if not a.startswith("--")]
    opts = dict(a[2:].split("=", 1) for a in sys.argv[1:] if a.startswith("--") and "=" in a)
    if not args or "id" not in opts:
        print(__doc__)
        sys.exit(1)
    root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    vid = opts["id"]
    out = opts.get("out", os.path.join(root, "projects", f"{vid}.voice.wav"))
    blocks = parse(args[0], float(opts.get("pause", .7)))
    voice, rate = opts.get("voice", "es-AR-TomasNeural"), opts.get("rate", "+0%")

    parts, lines, t = [np.zeros(int(.5 * SR), np.float32)], [], .5
    for b in blocks:
        pcm, words = asyncio.run(speak(b["text"], voice, rate))
        dur = len(pcm) / SR
        words = [[round(w0 + t, 3), round(w1 + t, 3), w] for w0, w1, w in words]
        lines.append({"id": b["id"], "t0": words[0][0] if words else t, "t1": words[-1][1] if words else t + dur, "words": words})
        parts += [pcm, np.zeros(int(b["pause"] * SR), np.float32)]
        t += dur + b["pause"]
        print(f"  {b['id']:<16} {t - dur - b['pause']:7.2f} s  +{dur:5.2f} s")

    mix = np.concatenate(parts)
    os.makedirs(os.path.dirname(out) or ".", exist_ok=True)
    wavfile.write(out, SR, (mix / (np.abs(mix).max() or 1) * .95 * 32767).astype(np.int16))
    lyr = os.path.join(os.path.dirname(out), f"{vid}.lyrics.js")
    with open(lyr, "w", encoding="utf-8") as f:
        f.write(f"// Generated by tools/narrate.py from {os.path.basename(args[0])} (voice {voice}).\n")
        f.write(f"registerLyrics({json.dumps(vid)}, {json.dumps(lines, ensure_ascii=False, indent=1)});\n")
    print(f"{out}: {len(blocks)} blocks, {len(mix) / SR:.1f} s · {lyr}")


if __name__ == "__main__":
    main()
