"""Word-level lyric timings from a song, as a script the studio loads next to a scene.

Usage:
    python tools/sync_lyrics.py <audio file> --id=my_video [--out=projects/my_video.lyrics.js]
                                [--model=medium] [--language=es] [--prompt-file=lyrics.txt]

Writes `registerLyrics('<id>', lines)`, where each line is { t0, t1, words: [[t0, t1, word], ...] }.
Load it together with the scene: studio.html?script=projects/my_video.lyrics.js,projects/my_video.js
--prompt-file (the lyrics as plain text, if you have them) makes the transcription far more accurate.
The default model is medium: small mishears names and jargon much more often. The first run downloads it (~1.5 GB) into the user's Hugging Face cache.
"""
import json
import os
import sys

from faster_whisper import WhisperModel


def main():
    args = [a for a in sys.argv[1:] if not a.startswith("--")]
    opts = dict(a[2:].split("=", 1) for a in sys.argv[1:] if a.startswith("--") and "=" in a)
    if not args or "id" not in opts:
        print(__doc__)
        sys.exit(1)
    audio, lyric_id = args[0], opts["id"]
    project_root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    out = opts.get("out", os.path.join(project_root, "projects", f"{lyric_id}.lyrics.js"))
    prompt = None
    if "prompt-file" in opts:
        with open(opts["prompt-file"], encoding="utf-8") as f:
            prompt = f.read()

    model = WhisperModel(opts.get("model", "medium"), device="cpu", compute_type="int8")
    segments, info = model.transcribe(audio, language=opts.get("language"), word_timestamps=True,
                                      initial_prompt=prompt, vad_filter=False, condition_on_previous_text=False)
    lines = []
    for seg in segments:
        words = [[round(w.start, 3), round(w.end, 3), w.word.strip()] for w in (seg.words or []) if w.word.strip()]
        if words:
            lines.append({"t0": words[0][0], "t1": words[-1][1], "words": words})

    os.makedirs(os.path.dirname(out) or ".", exist_ok=True)
    with open(out, "w", encoding="utf-8") as f:
        f.write(f"// Generated by tools/sync_lyrics.py from {os.path.basename(audio)}. Edit freely to fix misheard words.\n")
        f.write(f"registerLyrics({json.dumps(lyric_id)}, {json.dumps(lines, ensure_ascii=False, indent=1)});\n")
    n_words = sum(len(l["words"]) for l in lines)
    span = f"{lines[0]['t0']:.2f}s - {lines[-1]['t1']:.2f}s" if lines else "no vocals found"
    print(f"{out}: {len(lines)} lines, {n_words} words, {span} (language: {info.language})")


if __name__ == "__main__":
    main()
